### ISSUE TITLE
[bug] Fails to use QtGui.QStringListModel in Nuke12

### ISSUE THREAD

**Issue by fynnay** [adrianpueyo/KnobScripter#4]
On Linux in Nuke12.0v3 the panel fails to load because of a PySide2 error:

*log only shows partical paths because company privacy and stuff*

```python
Traceback (most recent call last):
  File "(...)/Nuke12.0v3/plugins/nukescripts/panels.py", line 153, in makeUI
    self.widget = self.widgetClass()
  File "~/.nuke/Scripts/KnobScripter/knob_scripter.py", line 1649, in __init__
    super(KnobScripterPane, self).__init__()
  File "~/.nuke/Scripts/KnobScripter/knob_scripter.py", line 123, in __init__
    self.initUI()
  File "~/.nuke/Scripts/KnobScripter/knob_scripter.py", line 357, in initUI
    self.script_editor = KnobScripterTextEditMain(self, self.script_output)
  File "~/.nuke/Scripts/KnobScripter/knob_scripter.py", line 2756, in __init__
    self.nukeCompleter.setModel(QtGui.QStringListModel())
AttributeError: 'module' object has no attribute 'QStringListModel'
```

My **workaround** so far is just to extend the PySide2 import part at the top like this:

```python
try:
    if nuke.NUKE_VERSION_MAJOR < 11:
        from PySide import QtCore, QtGui, QtGui as QtWidgets
        from PySide.QtCore import Qt
    else:
        from PySide2 import QtWidgets, QtGui, QtCore
        from PySide2.QtCore import Qt
        if nuke.NUKE_VERSION_MAJOR > 11:
            from PySide2.QtCore import QStringListModel
        else:
            from PySide2.QtGui import QStringListModel
except ImportError:
    from Qt import QtCore, QtGui, QtWidgets
```

**Comment by adrianpueyo** [comment]
This is resolved now! Thank you :)
