### ISSUE TITLE
KnobScripter bugs

### ISSUE THREAD

**Issue by aitorecheveste** [adrianpueyo/KnobScripter#9]
**- can't open preferences**

Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\code_gallery_dict.json
C:\Users\operator\.nuke\KS3\code_gallery_dict.json
{}
Traceback (most recent call last):
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\knob_scripter.py", line 457, in <lambda>
    triggered=lambda:self.open_multipanel(tab="ks_prefs"))
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\knob_scripter.py", line 1778, in open_multipanel
    nuke.ks_multipanel = MultiPanel(self, multipanel_parent, initial_tab = tab, lang = lang or self.script_editor.code_language)
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\knob_scripter.py", line 1957, in _init_
    self.initUI()
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\knob_scripter.py", line 1967, in initUI
    self.code_gallery = codegallery.CodeGalleryWidget(self.knob_scripter, None)
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\codegallery.py", line 253, in _init_
    self.initUI()
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\codegallery.py", line 287, in initUI
    self.change_lang(self.code_language, force_reload=True)
  File "Z:\RECURSOS\NUKE\NUKE_PATH/KnobScripter\KnobScripter\codegallery.py", line 363, in change_lang
    self.build_gallery_group(code_gallery_dict[lang], self.scroll_layout, lang=lang)
KeyError: 'python'

**- While it's open in the nuke console....**

DEBUG:root:Initializing KnobScripter
DEBUG:root:KS LOADED
DEBUG:Hiero:nukestudio.startServerIfEnabled
DEBUG:Hiero:nukestudio.startServer
...
...

**-When press te shortKey the window is always cut down (before appeared in the center of the screen)**

 **- Sometimes is closed when I read CSV files**

**Comment by sisoe24** [comment]
I do not think that KnobScripter3/develop branch is ready for public release and is likely working only on the owner local environment.
